### ISSUE TITLE
Similar tool that could be helpful for you

### ISSUE THREAD

**Issue by szaghi** [cburnicki/makeFortran#1]
Dear all,

Thank you for sharing your work. I am also _frustrated_ by the compilation cascade of large fortran projects using many modules, thus I created a tool to this aim (similar to your)

https://github.com/szaghi/FoBiS

I just like to let you know you are not alone :smile: Maybe FoBiS can be helpful for you.

Cheers.

**Comment by cburnicki** [comment]
Hey,

thanks for the hint! I actually just used this simple script for another simple unit test framework that I am playing around with. It's good to know FoBiS is there when I get to more complicated projects :smiley: .

BW

**Comment by szaghi** [comment]
You are welcome,
Good luck for your Fortran projects!

If you are interested to join us, we have created a group of Fortran addicted living in github

https://github.com/Fortran-FOSS-Programmers

The group aim is to develop FOSS Fortran projects and share our experiences to improve ourselfs.

Let me know if you are interested to join us.

See you soon.

**Comment by cburnicki** [comment]
Sure, I would be glad to join you. Since I am new to github and kind of new to fortran, I just can't promise to contribute something any time soon. But I guess I will get there eventually!

**Comment by szaghi** [comment]
@cburnicki 
Do not worry about if you will contribute actively or not on group's projects: even _sparse thoughts_ are welcome to improve the programming experience of all us as group members. I will inviting you to group right now.

See you soon.

P.S. we have gitter chat for general discussion of group 

 https://gitter.im/Fortran-FOSS-Programmers/General-Discussion

**Comment by cburnicki** [comment]
Thanks!
